language: scala
scala:
   - 2.11.11
   - 2.12.2
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - sbt coveralls